<a href="https://colab.research.google.com/github/Prof-Greipl/wif-640-machine-learning-sem/blob/master/IML_303_Neural_Network_with_Forward_Propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We add a loss function.

In [1]:
import numpy as np 
from sklearn import metrics

def activation(z, act_func):
    global _activation
    if act_func == 'relu':
       return np.maximum(z, np.zeros(z.shape))
    
    elif act_func == 'sigmoid':
      return 1.0/(1.0 + np.exp( -z ))

    elif act_func == 'linear':
        return z
    else:
        raise Exception('Activation function is not defined.')

        
class layer:
  def __init__(self,input_dim, output_dim, activation='relu'):    
    self.activation = activation
    self.input_dim = input_dim
    self.output_dim = output_dim # is this needed?? TODO
    if input_dim > 0:
      self.b = np.ones( (output_dim,1) ) 
      self.W = np.ones( (output_dim, input_dim) )
    
    self.A = np.zeros( (output_dim,1)) # added: we temp. store for A
  
  def setWeight(self, W ):
    self.W = W
    
  def setBias(self, b ):
    self.b = b
    
  def setActivation(self, A ): # changed
    self.Z =  np.add( np.dot(self.W, A), self.b)
    self.A =  activation(self.Z, self.activation)
  
  def print(self, layer_name=""):
    print(f"Konfiguration of Layer {layer_name} ------")
    if self.input_dim > 0:
      print(f"input_dim = {self.input_dim}")
      print(f"output_dim = {self.output_dim}")
      print(f"Activation = {self.activation}")
      print(f"W = ")
      print(self.W)
      print(f"b = ")
      print(self.b)
    else:
      print("This is an input layer..... ")
    #print("-----Finished Layer Config.")
  

class ModelNet:
  def __init__(self, input_dim):  
    
    self.neural_net = []
    self.neural_net.append(layer(0 , input_dim, 'irrelevant'))
    
  def addLayer(self, nr_neurons, activation='relu'):    
    layer_index = len(self.neural_net)
    input_dim = self.neural_net[layer_index - 1].output_dim
    new_layer = layer( input_dim, nr_neurons, activation)
    self.neural_net.append( new_layer)
    
  def forward_propagation(self, input_vec ):
    self.neural_net[0].A = input_vec
    for layer_index in range(1,len(self.neural_net)):    
       A_prev = self.neural_net[layer_index-1].A                       
       self.neural_net[layer_index].setActivation( A_prev )
    return  self.neural_net[layer_index].A
                             
  def summary(self):      
      for layer_index in range(len(self.neural_net)):        
        self.neural_net[layer_index].print(layer_index)
        
#Testing        
input_dim = 2
output_dim = 1
model = ModelNet( input_dim )
model.addLayer( 2, 'relu' )
model.addLayer( output_dim, 'linear' )
model.summary()


# Testing Loss for one feature vev (N=1)
X  = np.array([[1], [1]])
y_predicted = model.forward_propagation( X )
print(f" Shape of X  {X.shape}")
print(f" Result of propagation {y_predicted.shape}")
print(f" Result of propagation {y_predicted}")

# Testing for more more features (N=2)
X  = [[1,2], [1,2]]
y_predicted = model.forward_propagation( X )
print("\n")
print(f" Result of propagation {y_predicted.shape}")
print(f" Result of propagation {y_predicted}")


Konfiguration of Layer 0 ------
This is an input layer..... 
Konfiguration of Layer 1 ------
input_dim = 2
output_dim = 2
Activation = relu
W = 
[[1. 1.]
 [1. 1.]]
b = 
[[1.]
 [1.]]
Konfiguration of Layer 2 ------
input_dim = 2
output_dim = 1
Activation = linear
W = 
[[1. 1.]]
b = 
[[1.]]
 Shape of X  (2, 1)
 Result of propagation (1, 1)
 Result of propagation [[7.]]


 Result of propagation (1, 2)
 Result of propagation [[ 7. 11.]]
