# Prep: Analyze `metrics.mean_squared_error()`

In [0]:
import numpy as np 
from sklearn import metrics
y_true = np.array( [[0,1,2], [3,4,5]] )
y_predicted = np.array( [[1,1,1], [2,2,2]] )
error = metrics.mean_squared_error( y_true, y_predicted)
print (error)

diff =  y_true  - y_predicted
print( diff )
diff = diff * diff
print( diff )
print (16/6)


2.6666666666666665
[[-1  0  1]
 [ 1  2  3]]
[[1 0 1]
 [1 4 9]]
2.6666666666666665


# Adding a Loss Function

We add a loss function.

In [0]:
import numpy as np 
from sklearn import metrics

def activation(z, act_func):
    global _activation
    if act_func == 'relu':
       return np.maximum(z, np.zeros(z.shape))
    
    elif act_func == 'sigmoid':
      return 1.0/(1.0 + np.exp( -z ))

    elif act_func == 'linear':
        return z
    else:
        raise Exception('Activation function is not defined.')

def loss(y_true, y_predicted, loss_function='mse'):
   if loss_function == 'mse':
      return metrics.mean_squared_error( y_true, y_predicted)
   else:
      raise Exception('Loss metric is not defined.')
        
        
class layer:
  def __init__(self,input_dim, output_dim, activation='relu'):    
    self.activation = activation
    self.input_dim = input_dim
    self.output_dim = output_dim 
    if input_dim > 0:
      self.b = np.ones( (output_dim,1) ) 
      self.W = np.ones( (output_dim, input_dim) )
    
    self.A = np.zeros( (output_dim,1)) # added: we temp. store for A
  
  def setWeight(self, W ):
    self.W = W
    
  def setBias(self, b ):
    self.b = b
    
  def setActivation(self, A ): # changed
    self.Z =  np.add( np.dot(self.W, A), self.b)
    self.A =  activation(self.Z, self.activation)
  
  def print(self, layer_name=""):
    print(f"Konfiguration of Layer {layer_name} ------")
    if self.input_dim > 0:
      print(f"input_dim = {self.input_dim}")
      print(f"output_dim = {self.output_dim}")
      print(f"Activation = {self.activation}")
      print(f"W = ")
      print(self.W)
      print(f"b = ")
      print(self.b)
    else:
      print("This is an input layer..... ")
    #print("-----Finished Layer Config.")
  

class ModelNet:
  def __init__(self, input_dim):  
    
    self.neural_net = []
    self.neural_net.append(layer(0 , input_dim, 'irrelevant'))
    
  def addLayer(self, nr_neurons, activation='relu'):    
    layer_index = len(self.neural_net)
    input_dim = self.neural_net[layer_index - 1].output_dim
    new_layer = layer( input_dim, nr_neurons, activation)
    self.neural_net.append( new_layer)
    
  
  def forward_propagation(self, input_vec ):
    self.neural_net[0].A = input_vec
    for layer_index in range(1,len(self.neural_net)):    
       _A_Prev = self.neural_net[layer_index-1].A                       
       self.neural_net[layer_index].setActivation( _A_Prev )
    return  self.neural_net[layer_index].A
    
                             
  def summary(self):      
      for layer_index in range(len(self.neural_net)):        
        self.neural_net[layer_index].print(layer_index)
        


# Test

In [2]:
#Test        
input_dim = 2
output_dim = 1
model = ModelNet( input_dim )
model.addLayer( 2, 'relu' )
model.addLayer( output_dim, 'linear' )
model.summary()


# Testing Loss for one feature vev (N=1)
X  = [[1], [1]]
y_true =[[2]]
y_predicted = model.forward_propagation( X )
cost = loss( y_predicted, y_true)
print(f"Loss = {cost}")

# Testing for more more features (N=2)
X  = [[1,2], [1,2]]
y_true =np.array( [[2, 3]] )
y_predicted = model.forward_propagation( X )
print(f" Result of propagation {y_predicted}")
print(f" Shape of y_true {y_true}")

cost = loss( y_predicted, y_true)
print(f"Loss = {cost}")

Konfiguration of Layer 0 ------
This is an input layer..... 
Konfiguration of Layer 1 ------
input_dim = 2
output_dim = 2
Activation = relu
W = 
[[1. 1.]
 [1. 1.]]
b = 
[[1.]
 [1.]]
Konfiguration of Layer 2 ------
input_dim = 2
output_dim = 1
Activation = linear
W = 
[[1. 1.]]
b = 
[[1.]]
Loss = 25.0
 Result of propagation [[ 7. 11.]]
 Shape of y_true [[2 3]]
Loss = 44.5
