# Features and Labels

Arrays are relevant, because we use $N \times d$ matrices to define feature vectors and $N \times L$ matrices to define the labels. In simple cases, we have $L=1$.

# Arrays and Shapes

In [0]:
import numpy as np

# One dimensional array (Vektor)
a = np.array([1,2,3,4])
print ("\n--- One dimensional array ---")
print (f'Werte      :{a}' )
print (f'Dimension  :{a.ndim}' )
print (f'Shape      :{a.shape}' )
print (f'Size       :{a.size}')
print (f'Datatype   :{a.dtype}')
print (f'Element [1] :{a[1]}')

# Two dimensional array (Matrix)
a = np.array([[1,2,3,4], [5,6,7,8]])
print ("\n--- Matrix ---")
print (f'Werte      :{a}' )
print (f'Dimension  :{a.ndim}' )
print (f'Shape      :{a.shape}' )
print (f'Size       :{a.size}')
print (f'Datatype   :{a.dtype}')
print (f'Element [1,2] :{a[1][2]}')

# Very simple two dimensional array
a = np.array([[2]])
print ("\n--- Weights (needed for simple Neuron ---")
print (f'Werte      :{a}' )
print (f'Dimension  :{a.ndim}' )
print (f'Shape      :{a.shape}' )
print (f'Size       :{a.size}')
print (f'Datatype   :{a.dtype}')
print (f'Element [0][0] :{a[0][0]}')




--- One dimensional array ---
Werte      :[1 2 3 4]
Dimension  :1
Shape      :(4,)
Size       :4
Datatype   :int64
Element [1] :2

--- Matrix ---
Werte      :[[1 2 3 4]
 [5 6 7 8]]
Dimension  :2
Shape      :(2, 4)
Size       :8
Datatype   :int64
Element [1,2] :7

--- Weights (needed for simple Neuron ---
Werte      :[[2]]
Dimension  :2
Shape      :(1, 1)
Size       :1
Datatype   :int64
Element [0][0] :2


# Creating Arrays

np.linespace

* np.zeros
* np.ones
* reshape
* flatten (needed?)


In [0]:
import numpy as np
a = np.arange(10)
print (a)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
import numpy as np
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [0]:
import numpy as np
a = np.arange(0,1,0.4)
print(a)

[0.  0.4 0.8]


In [0]:
from numpy import pi
a = np.linspace(0, 2*pi, 10)
print( a )

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [0]:
a = np.zeros(( 3,4) ) 
print (a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
a = np.ones(( 3,4) ) 
print (a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [0]:
#Reshaping Basic Arrays
a = np.arange(6);
print (a)
b = a.reshape(2,3);
print (b)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [0]:
#Reshaping Basic Arrays
a = np.arange(24);
print (a)
b = a.reshape(2,3,4);
print (b)
print( b[1] )
print( b[0][0])

c = b[1].flatten()
print (c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[0 1 2 3]
[12 13 14 15 16 17 18 19 20 21 22 23]


# Operations on Arrays

In [0]:
a = np.array([1,2,3])

print (a+1)
print (a * 10)
print (a/2)
print (a*a)
print (np.sqrt(a))
print (np.exp(a))
print (np.sin(a))

[2 3 4]
[10 20 30]
[0.5 1.  1.5]
[1 4 9]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]


In [0]:
a = np.array([1,2,3])
b = np.array([-1,-2,-3])

print (a+b)
print (a*b)
print (a/b)


[0 0 0]
[-1 -4 -9]
[-1. -1. -1.]


# Indexing, Slicing and Striding

### Access with Index

In [0]:
import numpy as np
a = np.arange(12);
print (a)
b = a.reshape(1,2,3);
print (b)
print( b[1] )
print( b[0][0])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[0 1 2 3]


## Slice and Stride

In [0]:
a = np.arange(10)
print (a[:5])
print (a[:-3])
print (a[-3:-2])


b = a.reshape(2,5)
print( b[1:2,:3] )

c = np.arange(10)
z = c[2:5]
z[0] = 100
print( z )

[0 1 2 3 4]
[0 1 2 3 4 5 6]
[7]
[[5 6 7]]
[100   3   4]


# Exercise: Building Batches

In [0]:
import numpy as np
a = np.arange(50)
batch_size = 5  # also try with 7
batches = [ a[k : k+batch_size] for k in range(0,50, batch_size) ]
for i in range( len(batches) ):
  print ( batches[i] )

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]
[25 26 27 28 29]
[30 31 32 33 34]
[35 36 37 38 39]
[40 41 42 43 44]
[45 46 47 48 49]
