# Prep: Analyze `metrics.mean_squared_error()`

In [0]:
import numpy as np 
from sklearn import metrics
y_true = np.array( [[0,1,2], [3,4,5]] )
y_predicted = np.array( [[1,1,1], [2,2,2]] )
error = metrics.mean_squared_error( y_true, y_predicted)
print (error)

diff =  y_true  - y_predicted
print( diff )
diff = diff * diff
print( diff )
print (16/6)


2.6666666666666665
[[-1  0  1]
 [ 1  2  3]]
[[1 0 1]
 [1 4 9]]
2.6666666666666665


#Prep: Caluclate L2-Norm of Vector

In [0]:
v = np.array([-1,2,3])
print (np.square(v).sum())

14


# Adding a Loss Function

We add a loss function.

In [0]:
import numpy as np 
from sklearn import metrics

def loss(y_true, y_predicted, loss_function='mse'):
    if loss_function == 'mse':       
        return metrics.mean_squared_error( y_true, y_predicted)
    else:
        raise Exception('Loss metric is not defined.')
        
def sigma(z, act_func):
    global _activation
    if act_func == 'relu':
       return np.maximum(z, np.zeros(z.shape))
    
    elif act_func == 'sigmoid':
      return 1.0/(1.0 + np.exp( -z ))

    elif act_func == 'linear':
        return z
    else:
        raise Exception('Activation function is not defined.')

class Layer:
    def __init__(self,input_dim, output_dim, activation_function='linear'):    
        self.activation = activation_function
        self.input_dim = input_dim
        self.output_dim = output_dim 
        if input_dim > 0:
            #self.b = np.random.randn( output_dim, 1 )       
            #self.W = np.random.randn( output_dim, input_dim )
            #self.dW = np.random.randn( output_dim, input_dim )
            #self.db = np.random.randn( output_dim, 1 )
            self.b  = np.ones( (output_dim, 1) )       
            self.W  = np.ones( (output_dim, input_dim) )
        self.a = np.zeros( (output_dim,1) )

    
    def set_weight(self, W ):
        self.W = W
      
    def set_bias(self, b ):
        self.b = b
  
    def compute_activation(self, a ): 
        self.z =  np.add( np.dot(self.W, a), self.b)
        self.a =  sigma(self.z, self.activation)
    
    def print( self ):      
        print(f"\n====== Layer Info =======")
        print(f"a    = {self.a}")
        if self.input_dim > 0: 
          print(f"W   =  {self.W}")          
          print(f"b   =  {self.b}")  
    

class Model:
  def __init__(self, input_dim):  
      self.neural_net = []
      self.neural_net.append(Layer(0 , input_dim, 'irrelevant'))    


  def add_layer(self, nr_neurons, activation='relu'):    
      layer_index = len(self.neural_net)
      input_dim = self.neural_net[layer_index - 1].output_dim
      new_layer = Layer( input_dim, nr_neurons, activation)
      self.neural_net.append( new_layer )


  def forward_propagation(self, input_vec ):
      self.neural_net[0].a = input_vec
      for layer_index in range(1,len(self.neural_net)):    
        _A_Prev = self.neural_net[layer_index-1].a                       
        self.neural_net[layer_index].compute_activation( _A_Prev )
        
      return  self.neural_net[layer_index].a
  

  def summary(self):
      print("MODEL SUMMARY")
      for layer_index in range(len(self.neural_net)):        
        self.neural_net[layer_index].print()
        
      print("FINISHED MODEL SUMMARY")
        


# Test

In [5]:
#Test        
input_dim = 2
output_dim = 1
model = Model( input_dim )
model.add_layer( 2, 'relu' )
model.add_layer( output_dim, 'linear' )
model.summary()


# Testing Loss for one feature vev (N=1)
X      = np.array([[1,1]])
y_true = np.array([[2]])
y_predicted = model.forward_propagation( X.T )
cost = loss( y_predicted, y_true)
print(f"Loss = {cost}")

# Testing for more more features (N=2)
X       = np.array( [[1,1], [2,2]] )
y_true  = np.array( [[2, 3]] )
y_predicted = model.forward_propagation( X.T )
print(f" Result of propagation {y_predicted}")
print(f" Shape of y_true {y_true}")

cost = loss( y_predicted, y_true)
print(f"Loss = {cost}")

MODEL SUMMARY

====== Layer Info =======
a    = [[0.]
 [0.]]

====== Layer Info =======
a    = [[0.]
 [0.]]
W   =  [[1. 1.]
 [1. 1.]]
b   =  [[1.]
 [1.]]

====== Layer Info =======
a    = [[0.]]
W   =  [[1. 1.]]
b   =  [[1.]]
FINISHED MODEL SUMMARY
Loss = 25.0
 Result of propagation [[ 7. 11.]]
 Shape of y_true [[2 3]]
Loss = 44.5
